datalayer.settings:
  type: config_object
  label: Settings
  mapping:
    add_page_meta:
      type: boolean
    output_terms:
      type: boolean
    output_fields:
      type: boolean
    lib_helper:
      type: boolean
    global_entity_meta:
      type: integer
    vocabs:
      type: integer
