datalayer.settings:
  type: config_object
  label: Settings
  mapping:
    add_page_meta:
      label: 'Add entity meta data to pages'
      type: boolean
    output_terms:
      label: 'Include taxonomy terms'
      type: boolean
    output_fields:
      label: 'Include enabled field values'
      type: boolean
    lib_helper:
      label: 'Include "data layer helper" library'
      type: boolean
    entity_meta:
      label: 'Entity meta data'
      type: sequence
      sequence:
        type: string
    vocabs:
      label: 'Taxonomy'
      type: sequence
      sequence:
        type: string
    expose_user_details:
      label: 'Expose user details'
      type: string
    expose_user_details_roles:
      label: 'Expose user roles'
      type: sequence
      sequence:
        type: string
    expose_user_details_fields:
      label: 'Include enabled user field values'
      type: boolean
